sonar.projectKey=CV_Formulario_Lab02
sonar.projectName=Formulario CV Lab02
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=squ_5898491c0efb621810e46df546b7ae20c88f8e42
sonar.sourceEncoding=UTF-8